backend:
  name: github
  repo: CapReg/capitalregiongames # Path to your GitHub repository

  # Uncomment below to enable drafts
  publish_mode: editorial_workflow
media_folder: "src/images/" # Media files will be stored in the repo under src/images/uploads
public_folder: "/images/" # The src attribute for uploaded media will begin with /images/uploads

collections:
  # Our blog posts
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list"}
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "Chess" # Used in routes, e.g., /admin/collections/work
    label: "chess" # Used in the UI
    folder: "chess" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "description", name: "description", widget: "text" }
      - { label: "location", name: "location", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "Scrabble" # Used in routes, e.g., /admin/collections/work
    label: "scrabble" # Used in the UI
    folder: "scrabble" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "description", name: "description", widget: "text" }
      - { label: "location", name: "location", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }